FASTLANE := bundle exec fastlane

setup_fastlane:
	$(FASTLANE) init

distribute_develop_with_firebase:
	$(FASTLANE) distribute_develop_with_firebase

distribute_staging_with_firebase:
	$(FASTLANE) distribute_staging_with_firebase

deploy_to_googleplay:
	$(FASTLANE) deploy_to_googleplay
