# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :distribute_with_testflight do
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_testflight
  end

  desc "Push a new beta build to Firebase App Distribution"
  lane :distribute_with_firebase do
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    firebase_app_distribution(
      app: "1:123456789:ios:abcd1234",
      groups: "developer, tester"
    )
  end
end
