# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

IPA_PATH = '../build/ios/ipa/Runner.ipa'
APPSTORE_API_KEY_PATH = './fastlane/AppStoreApiKey/key.json'
CREDENTIALS_PATH = '../FirebaseCredentials/flutter-appdistribution-dev-firebase-adminsdk-lwjbw-f192fffebd.json'

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :distribute_with_testflight do
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      api_key_path: APPSTORE_API_KEY_PATH,
      ipa: IPA_PATH,
    )
  end

  desc "Push a new beta build to Firebase App Distribution"
  lane :distribute_with_firebase do
    firebase_app_distribution(
      app: "1:629913001281:ios:1dcdf263be40edb31455c0",
      groups: "developer, tester",
      release_notes: "Lots of amazing new features to test out!",
      ipa_path: IPA_PATH,
      service_credentials_file: CREDENTIALS_PATH
    )
  end
end
