# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

DEVELOP_APK_PATH = '../build/app/outputs/flutter-apk/app-develop-release.apk'
STAGING_APK_PATH = '../build/app/outputs/flutter-apk/app-staging-release.apk'
AAB_PATH = '../build/app/outputs/bundle/productRelease/app-product-release.aab'
CREDENTIALS_PATH = '../FirebaseCredentials/flutter-appdistribution-dev-firebase-adminsdk-lwjbw-f192fffebd.json'

default_platform(:android)

platform :android do

  desc "Push a new develop build to Firebase App Distribution"
  lane :distribute_develop_with_firebase do
    firebase_app_distribution(
      app: "1:629913001281:android:1979644468bce6891455c0",
      groups: "developer, tester",
      release_notes: "[DEVELOP]\n" + change_log_since_last_tag,
      apk_path: DEVELOP_APK_PATH,
      service_credentials_file: CREDENTIALS_PATH
    )
  end

  desc "Push a new staging build to Firebase App Distribution"
  lane :distribute_staging_with_firebase do
    firebase_app_distribution(
      app: "1:629913001281:android:1979644468bce6891455c0",
      groups: "developer, tester",
      release_notes: "[STAGING]\n" + change_log_since_last_tag,
      apk_path: STAGING_APK_PATH,
      service_credentials_file: CREDENTIALS_PATH
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy_to_googleplay do
    upload_to_play_store(
      aab_paths: AAB_PATH
    )
  end

  def change_log_since_last_tag
    # http://git-scm.com/docs/pretty-formats
    # <short hash> <commit title>
    return changelog_from_git_commits(commits_count: 10, pretty: '%h %s')
  end
end
